modLoader="javafml"
loaderVersion="[45,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/BingoLobby/issues"

[[mods]]
modId="bingolobby"
version="${file.jarVersion}"
displayName="BingoLobby"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bingolobby"
updateJSONURL="https://assets.melanx.de/updates/bingolobby.json"
authors="noeppi_noeppi"
description='''
A lobby for the Bongo mod.
'''

[[dependencies.bingolobby]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="bongo"
    mandatory=true
    versionRange="[1.19.4-3.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.4-4.4.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.19.2-4.2.10,)"
    ordering="NONE"
    side="BOTH"
