modLoader="javafml"
loaderVersion="[36,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/BingoLobby/issues"

[[mods]]
modId="bingolobby"
version="${file.jarVersion}"
displayName="BingoLobby"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bingolobby"
authors="noeppi_noeppi"
description='''
A lobby for the Bongo mod.
'''

[[dependencies.bingolobby]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="bongo"
    mandatory=true
    versionRange="[1.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="libx"
    mandatory=true
    versionRange="[1.16.3-1.0.60,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.4.5,)"
    ordering="NONE"
    side="BOTH"
