modLoader="javafml"
loaderVersion="[37,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/BingoLobby/issues"

[[mods]]
modId="bingolobby"
version="${file.jarVersion}"
displayName="BingoLobby"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bingolobby"
authors="noeppi_noeppi"
description='''
A lobby for the Bongo mod.
'''

[[dependencies.bingolobby]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.95,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="bongo"
    mandatory=true
    versionRange="[1.17.1-2.0.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1-2.1.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.17.1-2.0.22,)"
    ordering="NONE"
    side="BOTH"
