modLoader="javafml"
loaderVersion="[39,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/BingoLobby/issues"

[[mods]]
modId="bingolobby"
version="${file.jarVersion}"
displayName="BingoLobby"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bingolobby"
updateJSONURL="https://assets.melanx.de/updates/bingolobby.json"
authors="noeppi_noeppi"
description='''
A lobby for the Bongo mod.
'''

[[dependencies.bingolobby]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="bongo"
    mandatory=true
    versionRange="[1.18.1-2.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1-3.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.18.1-3.0.3,)"
    ordering="NONE"
    side="BOTH"
